# Generated by Django 3.2.7 on 2021-09-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_submitted', models.DateTimeField(auto_created=True)),
                ('subject', models.CharField(default='Newsletter - Atelier Arts & Forme', max_length=255)),
                ('body', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.topic')),
            ],
        ),
    ]
