# Generated by Django 3.2.7 on 2021-09-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_alter_newletter_subject_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletter',
            new_name='Newsletter',
        ),
    ]
