# Generated by Django 3.2.7 on 2021-09-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_rename_newletter_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='attachement_1',
            new_name='attachment_1',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='attachement_2',
            new_name='attachment_2',
        ),
    ]
