# Generated by Django 3.2.7 on 2021-09-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20210928_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='image_body1',
            new_name='image_body_1',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='image_body2',
            new_name='image_body_2',
        ),
    ]
