# Generated by Django 3.2.7 on 2021-09-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_auto_20210928_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='attachment_1',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='attachment_2',
        ),
    ]
