# Generated by Django 3.2.7 on 2021-10-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20210929_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='image_body_1',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='image_body_2',
        ),
    ]
