# Generated by Django 3.2.7 on 2021-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadable',
            name='file',
            field=models.FileField(upload_to='documents'),
        ),
    ]
