# Generated by Django 3.2.7 on 2021-10-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_downloadable_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadable',
            name='short_description',
            field=models.CharField(blank=True, max_length=455),
        ),
    ]
