# Generated by Django 3.2.7 on 2021-09-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_posted', models.TimeField()),
                ('content', models.TextField(default='Remplacer ce texte par le contenu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.topic')),
            ],
        ),
    ]
